import React from 'react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col flex-auto h-full items-center min-h-screen font-[family-name:var(--font-geist-sans)]`}
      >
        <header className="flex flex-col items-center justify-center w-full p-1  border border-black bg-indigo-800">
          header
        </header>
        <div className="flex flex-col grow p-1 h-full w-full">{children}</div>
        <footer className=" flex flex-col items-center justify-center w-full border border-black bg-red-800">
          footer
        </footer>
      </body>
    </html>
  )
}
