import React from 'react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-between min-h-screen font-[family-name:var(--font-geist-sans)] bg-teal-200`}
      >
        <header className="flex flex-col items-center justify-center w-full border border-black bg-indigo-200">
          header
        </header>
        {children}
        <footer className=" flex flex-col items-center justify-center w-full border border-black bg-red-200">
          footer
        </footer>
      </body>
    </html>
  )
}
